---
- name: instances
  ec2:
     key_name: "{{ web_ssh_key }}"
     group: 
        - "{{ web_security_group }}"
        - "{{ web_lb_security_group }}"
     instance_type: "{{ web_instance_type }}"
     region: "{{ web_region }}"
     image: "{{ web_ami_id }}"
     wait: true
     exact_count: "{{ web_count }}"
     count_tag: "{{ web_tag }}"
     instance_tags: "{{ web_tag }}"
     volumes:
        - device_name: /dev/sda1
          volume_type: "{{ web_vol_type }}"
          volume_size: "{{ web_vol_size }}"
          delete_on_termination: true
  register: ec2


- name: testing ssh port state 
  wait_for:
    host={{ item.public_ip }}
    port=22
    state={{ ssh_test_state }}
    delay=5
    timeout=300
  with_items: "{{ ec2.instances }}"

- name: inventory refresh
  meta: refresh_inventory

